language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="./vendor/bin/phpunit"

matrix:
    fast_finish: true
    include:
          # Minimum supported Symfony version and latest PHP version
        - name: "Lowest version on dependencies"
          php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak" SYMFONY_PHPUNIT_VERSION="5.7"

          # Test the latest stable release
        - name: "PHP 7.1"
        - php: 7.1
        - name: "PHP 7.2 with code coverage"
        - php: 7.2
          env: COVERAGE=true TEST_COMMAND="phpunit --coverage-clover build/logs/clover.xml" DEPENDENCIES="php-coveralls/php-coveralls:^2.1"

          # Test LTS versions
        - name: "PHP 7.2 with Symfony 3 components"
          php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^3"
        - name: "PHP 7.2 with Symfony 4 components"
          php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^4"

          # Latest commit to master
        - name: "PHP 7.2 with Unstable dependencies"
          php: 7.2
          env: STABILITY="dev"

    allow_failures:
          # dev stability is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - mkdir -p build/logs
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then php vendor/bin/php-coveralls -v; fi

